### ISSUE TITLE
[BUG] High delay of the `MapLibreLayer` on Android

### ISSUE THREAD

**Issue by josxha** [josxha/flutter_map_plugins#54]
### Package

flutter_map_maplibre

### Bug Description

The `MapLibreLayer` currently on Android a high delay and sometimes does not completely catch up. 
There are exceptions in the console.

### Steps to Reproduce

1. Launch the example app on android
2. Open the `flutter_map_maplibre` example page
3. Move the camera around

### Expected Results

No or a smaller delay and no exceptions.

### Actual Results

```console
E/flutter (26853): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Bad state: Use after release error
E/flutter (26853): #0      JReference.pointer (package:jni/src/jreference.dart:56:21)
E/flutter (26853): #1      MapLibreMap.moveCamera (package:maplibre/src/native/jni/org/maplibre/android/maps/MapLibreMap.dart:5280:27)
E/flutter (26853): #2      MapLibreMapStateJni.moveCamera.<anonymous closure> (package:maplibre/src/native/widget_state_jni.dart:221:14)
E/flutter (26853): #3      _platformIsolateMain.<anonymous closure> (dart:ui/platform_isolate.dart:142:51)
E/flutter (26853): #4      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
E/flutter (26853): 
```

### Code Sample

see example app

### Platforms

android

**Comment by josxha** [comment]
With flutter_map_maplibre version 0.0.4 and maplibre 0.2.1 there is still a slight delay since flutter and the maplibre map render separatly but it has become (almost) neglectable.
